when:
  - event: [push, cron, manual]

matrix:
  GODOT_VERSION:
    # - 3.6.2
    # - 4.5.2
    - 4.6.1

steps:
  - name: download_artifacts
    image: debian
    commands:
      - apt-get update && apt-get install -y wget unzip
      - ./download_artifacts.sh
      - ./extract_artifacts.sh
    environment:
      GODOT_VERSION: ${GODOT_VERSION}

  - name: Build Standard
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/arm64,linux/amd64
      registry: git.prijindal.click
      username: prijindal
      password:
        from_secret: PACKAGE_TOKEN
      dockerfile: Dockerfile.standard
      tags:
        - ${GODOT_VERSION}-standard
      provenance: mode=max
      build_args:
        GODOT_VERSION: ${GODOT_VERSION}
      repo: git.prijindal.click/${CI_REPO}

  - name: Build Mono
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/arm64,linux/amd64
      registry: git.prijindal.click
      username: prijindal
      password:
        from_secret: PACKAGE_TOKEN
      dockerfile: Dockerfile.mono
      tags:
        - ${GODOT_VERSION}-mono
      provenance: mode=max
      build_args:
        GODOT_VERSION: ${GODOT_VERSION}
      repo: git.prijindal.click/${CI_REPO}
