when:
  - event: [push, cron, manual]

matrix:
  GODOT_VERSION:
    - 4.6.1
    - 4.6.2

steps:
  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64
      registry: git.prijindal.click
      username: prijindal
      password:
        from_secret: PACKAGE_TOKEN
      auto_tag: true
      tags:
        - ${GODOT_VERSION}
      provenance: mode=max
      build_args:
        GODOT_VERSION: ${GODOT_VERSION}
      repo: git.prijindal.click/${CI_REPO}
      cache-from:
        - type=registry\\,ref=git.prijindal.click/${CI_REPO}:buildcache
      cache-to: type=registry,ref=git.prijindal.click/${CI_REPO}:buildcache,mode=max
